package com.nighthawk.spring_portfolio.mvc.teamAssignment;

// Import statements for JPA annotations
import jakarta.persistence.*;

/**
 * This class represents a TeamAssignment entity, which stores information about team memberships.
 */
@Entity // JPA annotation to mark this class as a database entity
@Table(name = "team_assignments") // JPA annotation to specify the table name in the database
public class TeamAssignment {

    /**
     * Unique identifier for the TeamAssignment record (auto-generated by the database using IDENTITY strategy).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the team the user belongs to.
     */
    @Column(name = "team_name", nullable = false) // JPA annotation for column name and NOT NULL constraint
    private String teamName;

    /**
     * Username of the user assigned to the team.
     */
    @Column(name = "username", nullable = false) // JPA annotation for column name and NOT NULL constraint
    private String username;

    // Default constructor (required by JPA)
    public TeamAssignment() {}

    // Parameterized constructor for creating a TeamAssignment object with specific team name and username
    public TeamAssignment(String teamName, String username) {
        this.teamName = teamName;
        this.username = username;
    }

    // Getters and Setters for accessing and modifying the fields
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTeamName() {
        return teamName;
    }

    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
}